### ISSUE TITLE
GeoNode Project Blueprint

### ISSUE THREAD

**Issue by ridoo** [GeoNodeUserGroup-DE/geonode-blueprint-docker#1]
We have worked out a [GeoNode Blueprint for Docker](https://github.com/GeoNodeUserGroup-DE/geonode-blueprint-docker/) which I transferred to the GeoNodeUserGroup-DE. The blueprint evolved from several upstream discussions[^1][^2] and [a project we did for a customer](https://github.com/52North/istg_geonode). Feel free to have a look at it, and of course you are highly welcomed to give feedback via issues or in the discussion here.

Main goal of this blueprint is to have a simplified view on the GeoNode actual setup with less cluttered configuration while preserving flexibility. At the time of writing GeoNode setup is much convoluted at several places so one have to watch out making changes to the defaults (lots of things have side effects). However, the blueprint cannot solve the upstream issues, but tries to narrow the focus on the most important parts. Another motivation is to establish (in my personal opinion) a better maintainable project setup[^2][^3] than [the official geonode-project](https://github.com/GeoNode/geonode-project) offers at the moment.

In collaboration with Pixida, we currently evaluate a similar setup [for the Thuenen Atlas](https://github.com/Thuenen-GeoNode-Development/thuenen_atlas) (may become public once @gannebamm gives a 👍 ) which is based on this blueprint and includes a more sophisticated development setup [using `devcontainer`](https://containers.dev/) configuration.

Please note, that there may be bugs, issues, and even conceptual things we did not spot (yet). So, again, we would be interested in feedback and how such a setup would be helpful or falls short in certain projects. In any case the blueprint may give others a good starting point.

/cc @matthesrieke 
/cc @mwallschlaeger 

[^1]: https://github.com/GeoNode/geonode-project/issues/471
[^2]: https://github.com/GeoNode/geonode-project/discussions/460
[^3]: https://lists.osgeo.org/pipermail/geonode-devel/2023-August/003335.html

**Comment by gannebamm** [comment]
The thuenen_atlas repo is now public. I will present the current development status at a the NFDI4Biodiversity Project Forum meeting on 5.12. Therefore it is really nice to see this joint progress of us! Thanks @ridoo

**Comment by gannebamm** [comment]
The setup was tested in our last development project [thuenen_atlas](https://github.com/Thuenen-GeoNode-Development/thuenen_atlas) and worked out quite well. 

@ridoo, since the above issue also contains a lot of history and explanation for this repo, could it be incorporated into the readme?
