### ISSUE TITLE
Email notification error

### ISSUE THREAD

**Issue by mkrueger-dev** [GeoNodeUserGroup-DE/geonode-blueprint-docker#9]
Hi,

I wanted to add a notice setting for account approval and get the following error when I do so:

<img width="602" alt="Screenshot 2024-05-23 at 09 18 08" src="https://github.com/user-attachments/assets/2bd22e05-e052-4bc7-bb0f-c968b7dbc64d">

In general the system is able to send emails e.g. when accounts got approved. 
Does anyone encounter the same Issue?

**Comment by ridoo** [comment]
Did you check if you have configured email? By default, the setting is `EMAIL_ENABLE=False`? For all email related configuration, you can refer to [the official geonode docs](https://docs.geonode.org/en/master/basic/settings/index.html#email-enable). Please close this ticket, if this resolves your issue.

**Comment by mkrueger-dev** [comment]
Email parameters are successfully configured via .env. In general the GeoNode installation is able to send emails. It does so for example when an user account was approved by the admin. However it is not possible to configure any notice setting option.

Could this be related to: https://github.com/GeoNode/geonode/issues/12111

**Comment by ridoo** [comment]
@mkrueger-dev I dived into it here, but unfortunately this issue is quite old (more than 10y) and got stuck in a dead end:

* https://github.com/pinax/pinax-notifications/issues/21
* https://github.com/pinax/pinax-notifications/pull/36
* https://github.com/pinax/pinax-notifications/pull/38

As this is not related to the blueprint, you can close it here.

**Comment by kikislater** [comment]
It could be interesting:
https://github.com/GeoNode/geonode/issues/12517

Also there is different behaviour with async true of false in .env

**Comment by ridoo** [comment]
@kikislater interesting, but does not apply to the reported issue here. See the linked issues in [my comment above](https://github.com/GeoNodeUserGroup-DE/geonode-blueprint-docker/issues/9#issuecomment-2334213017). You could test it on a GeoNode instance where you have admin permissions:

```
http://localhost/en-us/admin/pinax_notifications/noticesetting/add/
```

Not sure what you mean by different behaviour regarding to async ...
